CREATE TABLE autores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sexo VARCHAR(20),
    ano_nascimento INTEGER NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE livros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    data_publicacao DATE NOT NULL,
    autor_id BIGINT NOT NULL, -- Primeiro define a coluna
    CONSTRAINT fk_livro_autor FOREIGN KEY (autor_id) REFERENCES autores(id) -- Depois cria a FK
);

CREATE TABLE locatarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sexo VARCHAR(20),
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    telefone VARCHAR(20) NOT NULL,
    data_nascimento DATE NOT NULL
);

