CREATE TABLE alugueis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    livro_id BIGINT NOT NULL,
    locatario_id BIGINT NOT NULL,
    data_retirada DATE NOT NULL,
    data_devolucao DATE NOT NULL,
    CONSTRAINT fk_aluguel_livro FOREIGN KEY (livro_id) REFERENCES livros(id),
    CONSTRAINT fk_aluguel_locatario FOREIGN KEY (locatario_id) REFERENCES locatarios(id)
);
